name: Deploy Flask to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS_IPV4 }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        TARGET: ${{ secrets.TARGET_DIR }}

    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS_IPV4 }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          cd ${{ secrets.TARGET_DIR }}
          
   
          git pull origin main
          
     
          python3 -m venv venv
          source venv/bin/activate
          
    
          pip install -r requirements.txt
          

          pkill -f "gunicorn.*" || true
          

          nohup gunicorn -w 3 -b 0.0.0.0:80 main:app > gunicorn.log 2>&1 &
          
          echo "Flask application is running on port 80."
