name: Deploy Flask to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up SSH for EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS_IPV4 }}  # Dirección IP de tu EC2
        username: ${{ secrets.EC2_USER }}    # Usuario de tu EC2, probablemente "ubuntu"
        key: ${{ secrets.EC2_SSH_KEY }}      # Tu clave privada de EC2
        script: |
          cd ${{ secrets.TARGET_DIR }}        # Usar la variable de entorno TARGET_DIR
          git pull origin main                # Actualiza el código desde la rama main
          source venv/bin/activate            # Activa el entorno virtual
          pip install -r requirements.txt    # Instala las dependencias

    - name: Restart Flask application (Gunicorn)
      run: |
        sudo systemctl restart test-aws.service  # Reinicia el servicio Flask en EC2
